### ISSUE TITLE
Auto-deriving Arbitrary

### ISSUE THREAD

**Issue by llogiq** [nagisa/rust_arbitrary#4]
Similar to what I did for quickcheck, it should be easy enough to write a derive macro for `Arbitrary`, perhaps even with some shrinking support for simple types. Should I do it in another crate or send a PR your way to integrate it?

**Comment by blt** [comment]
@llogiq a PR would be delightful.

**Comment by nagisa** [comment]
I believe the usual approach is to just have a deriving crate as a directory within the primary repository. So yeah, a PR would be great.
